# Generated by Django 3.1.7 on 2022-05-07 13:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('state', models.CharField(choices=[('ENTRY', '+'), ('EXIT', '-')], max_length=10, verbose_name='State')),
            ],
            options={
                'verbose_name': 'Transaction Type',
                'verbose_name_plural': 'Transaction Types',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_date', models.DateTimeField(verbose_name='Occurrence Date')),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Value')),
                ('cpf', models.CharField(max_length=20, verbose_name='CPF')),
                ('card', models.CharField(max_length=20, verbose_name='Card')),
                ('store_owner', models.CharField(max_length=50, verbose_name='Store Owner')),
                ('store_name', models.CharField(max_length=50, verbose_name='Store Name')),
                ('slug', models.SlugField(unique=True)),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cnab.transactiontype', verbose_name='Transaction Type')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ('store_name',),
            },
        ),
    ]
