# Generated by Django 3.1.7 on 2022-05-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='state',
            field=models.CharField(choices=[('+', 'ENTRY'), ('-', 'EXIT')], max_length=10, verbose_name='State'),
        ),
    ]
